
server:
    port: 8982
  logging:
    file: flow.log
  
  cxflow:
    bug-tracker: GitLab
    bug-tracker-impl:
    - GitLab
    branches:
    - master
    filter-severity:
    filter-category:
    - SQL_Injection
    - Stored_XSS
    - Reflected_XSS_All_Clients
    filter-cwe:
    filter-status:
    #   - Urgent
    #   - Confirmed
    #mitre-url: https://cwe.mitre.org/data/definitions/%s.html
    #wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
    codebash-url: https://checkmarx-demo.codebashing.com/courses/
  
  checkmarx:
    version: 9.0
    scope: access_control_api sast_rest_api 
    username: ###<username>###
    password: ###<password>###
    client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
    base-url: http://localhost
    team: /CxServer/SP/Company
    url: ${checkmarx.base-url}/cxrestapi
    #WSDL Config
    portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
    sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
    portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
    sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  
  
  gitlab:
    webhook-token: 12345
    token: ###<gitlabtoken>###
    url: https://gitlab.com/###<gitlaborg>###
    api-url: https://gitlab.com/api/v4/
    false-positive-label: false-positive
    block-merge: true