version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Install CxCLI Plugin
          command: |
            wget -O ~/cxcli.zip https://download.checkmarx.com/8.9.0/Plugins/CxConsolePlugin-8.90.0.zip
            unzip ~/cxcli.zip -d ~/cxcli
            chmod +x ~/cxcli/runCxConsole.sh
      - run:
          name: Execute CxSAST Scan
          command: |
            ~/cxcli/runCxConsole.sh Scan -CxServer "${CX_SERVER}" -CxUser "${CX_USER}" -CxPassword "${CX_PASSWORD}" -ProjectName "${CX_TEAM}\\${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}" -preset "${CX_PRESET}" -LocationType folder -LocationPath ~/ -SASTHigh ${CX_HIGH} -SASTMedium ${CX_MEDIUM} -SASTLow ${CX_LOW} -Comment "git ${CIRCLE_BRANCH}@${CIRCLE_SHA1}" -verbose